"""CreateEntityGenerator —— 代码生成器"""

from app.ai.builder.base import BaseGenerator, GeneratedArtifact


class CreateEntityGenerator(BaseGenerator):
    generator_name = "create_entity"

    def generate(self, payload: dict, context: dict) -> GeneratedArtifact:
        module_name = payload.get("name", "unknown")
        display_name = payload.get("display_name", module_name)
        content = f"# Generated by Builder Agent\n# Module: {module_name}\n# Action: {self.generator_name}\n\n"
        path = f"generated/{module_name}/__init__.py"
        return GeneratedArtifact(artifact_type=self.generator_name, path=path, content=content)
